import 'package:flutter/material.dart';

const Map<String, IconData> iconMap = {
  'restaurant': Icons.restaurant,
  'directions_car': Icons.directions_car,
  'shopping_bag': Icons.shopping_bag,
  'movie': Icons.movie,
  'receipt': Icons.receipt,
  'local_hospital': Icons.local_hospital,
  'school': Icons.school,
  'more_horiz': Icons.more_horiz,
  'home': Icons.home,
  'two_wheeler': Icons.two_wheeler,
  'flight': Icons.flight,
  'fitness_center': Icons.fitness_center,
  'pets': Icons.pets,
  'coffee': Icons.coffee,
  'phone_android': Icons.phone_android,
  'wifi': Icons.wifi,
  'sports_esports': Icons.sports_esports,
  'checkroom': Icons.checkroom,
  'savings': Icons.savings,
  'card_giftcard': Icons.card_giftcard,
  'child_care': Icons.child_care,
  'local_gas_station': Icons.local_gas_station,
  'build': Icons.build,
  'brush': Icons.brush,
  'account_balance_wallet': Icons.account_balance_wallet,
  'work': Icons.work,
  'trending_up': Icons.trending_up,
  'store': Icons.store,
  'attach_money': Icons.attach_money,
  'card_travel': Icons.card_travel,
  'laptop': Icons.laptop,
  'star': Icons.star,
  'category': Icons.category,
  'account_balance': Icons.account_balance,
  'credit_card': Icons.credit_card,
  'payment': Icons.payment,
  'money': Icons.money,
};

IconData getIconData(String name) => iconMap[name] ?? Icons.category;

final List<String> availableIcons = iconMap.keys.toList();
